#!/usr/bin/env python3

import argparse
import contextlib
import logging
import os
import re
import shlex
import subprocess
import sys
from collections.abc import Generator

import requests

logger = logging.getLogger(__name__)

logging.getLogger("urllib3").setLevel(logging.WARNING)

SEMVER_REGEX = (
    r"(?P<version>(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*))"
    r"(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?"
    r"(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?"
)


@contextlib.contextmanager
def working_directory(path: str | None) -> Generator[None, None, None]:
    """Change working directory."""
    cwd = os.getcwd()
    if path is not None:
        os.chdir(path)
    try:
        yield
    finally:
        os.chdir(cwd)


class CommandNotFoundError(FileNotFoundError):
    def __init__(self, command: list[str]) -> None:
        msg = (
            f"\n\nPROCESS: {shlex.join(command)}"
            f"\n\nSTDERR:  {command[0]}: command not found"
        )
        super().__init__(msg)


class CommandError(RuntimeError):
    def __init__(self, completed: subprocess.CompletedProcess[bytes]) -> None:
        self.command = completed.args
        self.returncode = completed.returncode
        self.stdout = completed.stdout.decode("utf-8").splitlines()
        self.stderr = completed.stderr.decode("utf-8").splitlines()
        msg = (
            f"\n\nPROCESS: {shlex.join(completed.args)}"
            f"\n\nRETURN:  {completed.returncode}"
            f"\n\nSTDOUT:\n{completed.stdout.decode('utf-8')}"
            f"\n\nSTDERR:\n{completed.stderr.decode('utf-8')}"
        )
        super().__init__(msg)


def command_run(
    *args: str,
    _env: dict[str, str] | None = None,
    _ok_code: list[int] | None = None,
) -> None:
    command_parts = [str(x) for x in args]

    logger.debug(f"COMMAND: {shlex.join(command_parts)}")

    try:
        completed = subprocess.run(  # noqa: S603
            command_parts,
            shell=False,
            check=False,
            capture_output=True,
            env=_env,
        )
    except FileNotFoundError:
        raise CommandNotFoundError(command_parts)

    if completed.returncode not in (_ok_code or [0]):
        raise CommandError(completed)


def toolchain_version(version: str | None) -> tuple[int, ...]:
    if version is None:
        return ()
    try:
        match = re.fullmatch(
            r"(0|[1-9]\d*)(?:\.(0|[1-9]\d*)(?:\.(0|[1-9]\d*))?)?", version
        )
        return tuple(int(x) for x in match.groups() if x)
    except AttributeError as error:
        raise ValueError("Invalid version string") from error


def toolchain_str(toolchain: tuple[int, ...]) -> str:
    return ".".join(tuple(map(str, toolchain)))


def resolve_compatible_crate_version(
    crate: str, toolchain: tuple[int, ...]
) -> str | None:
    response = requests.get(
        f"https://crates.io/api/v1/crates/{crate}/versions?per_page=100&sort=semver",
        timeout=10,
    )
    for version in response.json()["versions"]:
        crate_version = version["num"]
        rust_version = toolchain_version(version["rust_version"])
        if rust_version <= toolchain:
            return crate_version
    return None


def cargo_update(
    crate_with_version: str, new_version: str, toolchain: tuple[int, ...]
) -> None:
    logger.info(f"Updating crate {crate_with_version} to {new_version}")
    command_run(
        "cargo",
        f"+{toolchain_str(toolchain)}",
        "update",
        f"{crate_with_version}",
        "--precise",
        new_version,
    )


def handle_update_error(error: CommandError, toolchain: tuple[int, ...]) -> None:
    for line in error.stderr:
        match = re.fullmatch(
            rf"required by package `(?P<crate>\S+) v{SEMVER_REGEX}`", line
        )
        if match:
            crate_with_version = f"{match['crate']}@{match['version']}"
            logger.debug(f"The crate {crate_with_version} needs an update")
            new_version = resolve_compatible_crate_version(match["crate"], toolchain)
            return try_update(crate_with_version, new_version, toolchain)
    raise RuntimeError("Failed to parse 'cargo update' traces")


def try_update(crate: str, version: str | None, toolchain: tuple[int, ...]) -> None:
    try:
        cargo_update(crate, version, toolchain)
    except CommandError as error:
        handle_update_error(error, toolchain)
    else:
        logger.debug("Update done")


def cargo_check(toolchain: tuple[int, ...]) -> None:
    logger.info("Checking build...")
    command_run("cargo", f"+{toolchain_str(toolchain)}", "check")


def handle_check_error(error: CommandError, toolchain: tuple[int, ...]) -> None:
    for line in error.stderr:
        match = re.fullmatch(
            rf"cargo update (?P<crate>[^@]+)@{SEMVER_REGEX} \-\-precise ver", line
        )
        if match:
            crate_with_version = f"{match['crate']}@{match['version']}"
            logger.debug(f"The crate {crate_with_version} needs an update")
            new_version = resolve_compatible_crate_version(match["crate"], toolchain)
            try_update(crate_with_version, new_version, toolchain)
            return try_check(toolchain)

        match = re.fullmatch(
            rf"error: failed to download `(?P<crate>\S+) v{SEMVER_REGEX}`", line
        )
        if match:
            crate_with_version = f"{match['crate']}@{match['version']}"
            logger.debug(f"The crate {crate_with_version} needs an update")
            new_version = resolve_compatible_crate_version(match["crate"], toolchain)
            try_update(crate_with_version, new_version, toolchain)
            return try_check(toolchain)

    raise RuntimeError("Failed to parse 'cargo check' traces")


def try_check(toolchain: tuple[int, ...]) -> None:
    try:
        cargo_check(toolchain)
    except CommandError as error:
        handle_check_error(error, toolchain)
    else:
        logger.info("Done")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Update dependencies compatible with a toolchain"
    )

    parser.register("type", "semver", toolchain_version)
    parser.add_argument("TOOLCHAIN", type="semver", help="the toolchain override")
    parser.add_argument(
        "-C",
        metavar="PATH",
        dest="working_directory",
        help="change the working directory",
    )
    parser.add_argument("-v", "--verbose", action="store_true", help="show debug logs")

    if len(sys.argv) > 1 and sys.argv[1] == "compat":
        del sys.argv[1]

    args = parser.parse_args()

    logging.basicConfig(
        format="%(levelname)s: %(message)s",
        level=logging.DEBUG if args.verbose else logging.INFO,
    )

    with working_directory(args.working_directory):
        try_check(args.TOOLCHAIN)

    return 0


if __name__ == "__main__":
    sys.exit(main())
